# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MediastreamSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MediastreamSampleApp
  pod 'MediastreamPlatformSDKxC', '~> 2.0.2'

end
